# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec403310e2d29829a376c8fd34c0b91d72dfd37446b4e344f50b0b724f0b99122c5f8223b3530b40934871bfbc16cb4d700bda63f8dd2dda84209fe489eb44eb

test:
  secret_key_base: 1018f26b84a2f74fe4e5521b815549a551e0afea080a6a0b326ffdbd5a274f144b4a81d32be5a84443c5687aa62a39f22c5bd94913449ca378687e54d89f62f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
